language: cpp

compiler:
  - clang
  - gcc

jobs:
  include:
    - stage: building and testing
      script:
        - mkdir build
        - cd build
        - cmake ..
        - cmake --build ..
        - ./tryingout_ut
